name: traventico

services:

  nest:
    image: andr13/traventico-backend-new:latest
    container_name: nest-app-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SANITY_PROJECT_ID: ${SANITY_PROJECT_ID}
      SANITY_DATASET: ${SANITY_DATASET}
      SANITY_API_VERSION: ${SANITY_API_VERSION}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DBNAME: ${POSTGRESQL_DBNAME}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
    ports:
      - "4000:4000"
    command: >
      sh -c "npx prisma migrate deploy &&
            node dist/prisma/seed.js &&
             node dist/src/main.js"

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nest
